### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Eninspace** [TelegramMessenger/MTProxy#364] opened 2020-01-06 16:49 UTC
If in config there is --ipv6 argument, curl to localhost doesn't work.

**Comment by Eninspace** [comment] 2020-01-09 18:49
I tried it on two Ubuntu 18.04 both returned the problem

**Comment by LetzteInstanz** [comment] 2020-01-13 09:40
Duplicate of #198

**Comment by LetzteInstanz** [comment] 2020-01-13 09:41
#198

**Closed as completed** 2020-01-13 15:39 UTC
