### ISSUE TITLE
Run MTProxy in Windows server

### ISSUE THREAD

**Issue by ehaidari** [TelegramMessenger/MTProxy#43] opened 2018-06-01 07:24 UTC
How we can run **official** MTProxy on windows server 2012 R2?

**Comment by stek29** [comment] 2018-06-01 08:17
Run the docket image.
Duplicate of at least two other issues.

**Comment by Metal-Ghost** [comment] 2018-06-01 12:01
hi if you can.
install VMWare 12 and install ubuntu and try to run MTProto-Proxy

**Comment by seega** [comment] 2018-06-01 13:27
@ehaidari https://github.com/TelegramMessenger/MTProxy/issues/5#issuecomment-393505406

**Closed as completed** 2018-06-01 18:01 UTC
Labels: duplicate

**Comment by mr-459** [comment] 2020-06-01 13:50
y78i78
docker not may
at docker you get errore: you cant run linux prodects under windows
